User/vpidatala/task14647120
Azure/OnBoardVMInsights pull request #38
Opened 2023-08-07 23:17 UTC by vpidatala94

2023-08-16 17:13 UTC, mthompson83 requested changes
I'm only part way through, but I see many of the needed changes apply across the script. I'm "finishing" my review so making changes can get underway. Please address the specific comments. Also, where they address code structure that shows up elsewhere in the code, apply the structural changes everywhere.

2023-08-16 17:13 UTC, mthompson83 commented on Install-VMInsights.ps1
> +#
trailing whitespace

2023-08-21 04:04 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +#
used +$ command in VSCODE to resolve all trailing whitepsaces.

2023-08-21 05:56 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    [Parameter(mandatory = $false, ParameterSetName = 'AzureMonitoringAgent')][switch]$ProcessAndDependencies,
Apologies Mike, failed to check on this before, I did not understand this comment

2023-08-22 08:54 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    if ($extension) {
making no assumptions that the object cannot be null.

2023-08-22 09:11 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            Write-Output ("$VMName : Failed to remove extension : $ExtensionType")
comment obsolete

2023-08-22 09:16 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            $statusCode = $removeResult.StatusCode
if ($removeResult) {
        if ($removeResult.IsSuccessStatusCode) {
            $message = "$VMName : Successfully removed $ExtensionType"
            Write-Verbose($message)
        }
        else {
            $statusCode = $removeResult.StatusCode
            $ErrorMessage = $removeResult.ReasonPhrase
            $message = "$VMName : Failed to remove $ExtensionType. StatusCode = $statusCode. ErrorMessage = $ErrorMessage."
            $OnboardingStatus.Failed += $message
            throw $message
        }
    } else {
        $message = "$VMName : Failed to remove $ExtensionType"
        $OnboardingStatus.Failed += $message
        throw $message
    }

In the code here -> if $removeResult is null, we are not referencing the statusCode and ReasonPhrase, the message in this case would be "$VMName : Failed to remove $ExtensionType"

2023-08-22 09:21 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        throw $_
This is intentional, the idea is to capture the exception thrown in parent catch section containing Display-Exception $_ because the customer needs to know that the extension could not be removed.

2023-08-22 09:28 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    if ($extension) {
if ExtensionType does not already exist in VM, $extension in null, if it is $null there is no point checking the settings sections of the extension

2023-08-22 09:31 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        $extension = Get-VMExtension -VMName $VMName -VMResourceGroup $VMResourceGroupName -ExtensionType $ExtensionType
replaced Get-VMExtension with Get-AzVMExtension, comment removed.

2023-08-22 09:32 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        if ($removeResult) {
Understood!

2023-08-22 09:34 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            $removeResult = Remove-AzureRmVMExtension -ResourceGroupName $VMResourceGroupName -VMName $VMName -Name $ExtensionName -Force
replaced with  Remove-AzVMExtension

2023-08-22 09:36 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            $removeResult = Remove-AzureRmVMExtension -ResourceGroupName $VMResourceGroupName -VMName $VMName -Name $ExtensionName -Force
Replaved Get-VMExtension with Get-AzVMExtension which always return the extension object, if extension object isn't present we bail out from remove extension funtion with the message -  $message = $VMName + " : " +  $ExtensionName + " with name : " + $ExtensionName + " does not exist"

2023-08-22 09:37 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        if ($removeResult) {
making no assumptions that Remove-AzVMExtension not return null

2023-08-22 16:22 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            $dcrassociation = New-AzDataCollectionRuleAssociation -TargetResourceId $TargetResourceId -AssociationName $dcrassociationName -RuleId $DcrResourceId
In the code New-AzDataCollectionRuleAssociation is preceeded by Get-AzDataCollectionRuleAssociation, where we are checking if the VM in question here already mapped with the DCRID we want the VM to onboard it with, if so we are returning from the function. This code path has been tested.

2023-08-22 16:43 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            if ($dcrassociation -is [ErrorResponseCommonV2Exception]) {
To note this is a temp fix because the team owning -> New-AzDataCollectionRuleAssociation is working on making updates to the return object of this api to showcase the provisioning state as currently the API throws ErrorResponseCommonV2Exception in case of error and in failure. I added an extra check here to check if the DCRA is associated to the right DCR ID.
if (!$dcrassociation -or $dcrassociation -is [ErrorResponseCommonV2Exception] -or ($dcrassociation.DataCollectionRuleId -eq $DcrResourceId)) {
                #Tmp fix task:- 21191002
                throw}

2023-08-22 16:52 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +function Install-DCRAssociation {
a dcr association is an extension resource -> https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/datacollectionruleassociations , in line with our naming convention for Install-VMExtension for DA and AMA, Lastly, based on the powershell naming convention, Install is the most suited verb for this association.

2023-08-23 01:58 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    #The Customer is responsible to uninstall the DCR Association themselves
the content explains never takes responsibility of removing DCRA, the design thought implicates that if a VM is associated with a DCR that request both DA data and InsightMetrics and then at a later point for some reason decides to not have DA data reaching the workspace. If the customer decides to associated another DCR to the VM with only InsightsMetrics Collection enabled and not DA data for this purpose, instead of editing the already connected DCR. The consequence of this situation is that DA data is still flowing to the workspace. Based on the earlier discussion on removing an extension as part of onboarding script is not a good idea.  Thus, this comment explains that design decision. We must also include this in our documentation. We can sync up on this to discuss further.

2023-08-23 04:58 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        [Parameter(Mandatory = $true)][string]$TargetResourceId,
Got it!

2023-08-23 06:05 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +                $statusCode = $removeResult.StatusCode
I followed the existing coding style in the script - as shown here in the original script -  $message = "$VMName : Extension $ExtensionType already configured for this workspace. Provisioning State: " + $extension.ProvisioningState + " " + $extension.Settings , for learning what are the issues with the existing coding style?

2023-08-23 06:12 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        if ($removeResult) {
saved for future reference, understood

2023-08-24 01:17 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        $dcrAssociationList = Get-AzDataCollectionRuleAssociation -TargetResourceId $TargetResourceId
The code was tested with this scenario I did not have the error, but will gain from your wisdom and add the cmdlet to make sure we always get an array.

2023-08-24 18:57 UTC, mthompson83 commented on Install-VMInsights.ps1
> +function Install-DCRAssociation {
Everything in Azure is a "Resource".

"Install" suggests placing executables onto a system.

Take your hint from the name of the underlying cmdlet being used, `New-AzDataCollectionRuleAssociation`.

2023-08-24 19:05 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +function Install-DCRAssociation {
Thank you for comments! Replaced the name to New-DCRAssociation

2023-08-25 17:20 UTC, mthompson83 requested changes
More comments to follow.

2023-08-25 17:31 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +                #Tmp fix task:- 21191002
this should ultimately be replaced with $dcrassociation.ProvisioingState != Success

2023-08-25 18:23 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    if (!$extension) {
have replaced Get-AzVMExtension with Get-VMExtension (user-defined function) that looksup extension based on extension type, with this function if  $extensionType is not found in the list of extensions under the VM, we must get a $null object.

2023-08-25 18:36 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        Set-FailureMessage "$vmName : Failed to remove $ExtensionType."
the messages are not exactly the same, two error messages are - 

 Set-FailureMessage "$vmName : Failed to remove $ExtensionType."

  Set-FailureMessage "$vmName : Failed to remove $ExtensionType. StatusCode = $statusCode. ErrorMessage = $ErrorMessage."

but if this is causing confusion, I will work to change the names

2023-08-25 18:40 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    if (-not $removeResult) {
although the documentation for Remove-AzVMExtension indicates the response - [PSAzureOperationResponse](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.models.psazureoperationresponse)

but it does not indicate that under all circumstances this object would never be $null, thus making no assumptions, can we sync to discuss

2023-08-25 18:56 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    if (-not $removeResult) {
Since I  have not been able to demonstrate the error I am talking about and the we authoritative documentation on how the output would be. Going forward and removing $removeResult

2023-08-25 19:11 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        throw $_
the intention of these messages are messages to help the Customer what errors they are facing and Engineer for troubleshooting. All exception is intentionally being thrown to the highest level catch clause for code-reusability. I re-tracked the path of this function and I see the exceptions are being handled in the catch clause -  catch {
        Display-Exception $_
    } this is the expectation.

2023-08-25 19:48 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            Write-Output($message)
Understood!

2023-08-25 20:43 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    #The Customer is responsible to uninstall the DCR Association themselves
first time onboarding - the script can onboard extensions and associate a DCR to a VM/VMss
Legacy agent migration -> the script will not remove LA but will add AMA, DA will still be installed in the extension but if the customer did not DA data collection from the DCR, the DA data does not flow. (Not removed DA extension - this is based on our initial discussions of an onboarding script should not be remove DA extension)

Re-configuration is tricky - 
a VM can have multiple DCRs associated. 
1.  The script supports associating multiple DCRs to a VM
2.  It will not remove a DCRA for the customer and replace it with another DCR, that is left with the Customer to perform, we can add documentation on how to do it.

2023-08-25 21:14 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        $dcrAssociationList = Get-AzDataCollectionRuleAssociation -TargetResourceId $vmId
Thank you Mike! Yes that make sense! But we already have a comment here - # A VM may have zero or more Data Collection Rule Associations that explains the comment

2023-08-25 21:16 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +        $dcrAssociationList = Get-AzDataCollectionRuleAssociation -TargetResourceId $vmId
Understood got it.

2023-08-25 21:43 UTC, mthompson83 requested changes
More comments to follow

2023-08-25 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $statusCode = $removeResult.StatusCode
How does the use of the `statusCode` and `$errorMessage` variables improve code readability?

2023-08-25 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if (!$removeResult.IsSuccessStatusCode) {
Strong recommendation: When the then and else clauses are of significantly different lengths, make the then clause the shorter one.

2023-08-25 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if (!$removeResult.IsSuccessStatusCode) {
Simplify:

replace 
```
    if (condition) {
        # long code block
        throw ...
    }
    else {
        # small code block
    }

    # implicit function return
```
with
```
    if ( ! condition) {
        # small code block
        return
    }

    # long code block
    throw ...
```

2023-08-25 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
I don't see a global setting for error action handling. Therefore, cmdlets may error and continue.

2023-08-25 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if ($dcrAssociation.DataCollectionRuleId -eq $DcrResourceId) {
Question: What are we doing to prevent associations with multiple DCR that are functionally equivalent? Or is that OK?

2023-08-25 22:19 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +    try {
The observation isn't correct Mike :) perhaps it is because of incorrect naming causing the confusion - Set-FailureMessage should be something like Append-FailureMessag. here failure messages in Get-VMExtension and Set-FailureMessage are appended in Onboarding, so all messages are captured. The exception being thrown in being captured at the parent catch clause at line 990. Although there is no need to re-throw the same exception, I will fix that.

2023-08-28 14:19 UTC, mthompson83 commented on Install-VMInsights.ps1
> +	    [Parameter(mandatory = $true)][hashtable]$OnboardingStatus
indentation

2023-08-28 19:47 UTC, mthompson83 requested changes
More connects to follow.

2023-08-28 19:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                if ($extension.Settings.ToString().Contains($PublicSettings.enableAMA)) {
Assume `$PublicSettings` does **not** have a key-value pair for "enableAMA". `.Contains` will always evaluate to `$true`. The message "... already configured with AMA enabled. ..." will always be displayed. It is incorrect.

2023-08-28 19:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            $result = Set-AzVMExtension @parameters
Looking at our `Update-VMExtensionVersion.ps1`, I see we are using `-ForceRerun True`. Why is this not needed in the update case?

2023-08-28 19:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Remove-VMExtension -VMObject $VMObject `
Are there no errors/exceptions that need to be handled? Is it possible to throw an exception, and because it isn't handled, the old extension was removed, but the new one isn't added?

2023-08-28 19:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($PSCmdlet.ShouldProcess($VMName, "install extension $ExtensionType")) {
Scope the ShouldProcess down only the code that needs to be protected.

2023-08-28 19:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($PSCmdlet.ShouldProcess($VMName, "install extension $ExtensionType")) {
Consider reducing conditional nesting by

```
if (! $PSCmdlet.ShouldProcess($VMName, "install extension $ExtensionType")) {
    return
}

# ... all the code currently in the then block.

2023-08-28 21:58 UTC, mthompson83 requested changes
More to follow

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
>      if ($extension) {
I know this was following the model of the existing code, but a) it wasn't a good design, and b) adding additional extensions into the mix only makes it worse. A function called `Install-VMExtension` should have **no** code in it that is specific to a specific extension. 

Refactor into
- A function that gets current settings for a given extension.
- A function that installs/updates an extension for a VM.
- A function for each extension type that uses the two functions above, with the extension specific code in between.

In general, any function that has block, or blocks, of code in it that are conditionally executed based on parameter values, and the parameter values can be determined in the caller at compile time, then the function should be refactored.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                        Write-Output "$vmName : Extension $ExtensionType present, run with -ReInstall again to move to new workspace. Provisioning State: $($extension.ProvisioningState) `n $($extensi
Changing this to `Write-Output` from `Write-Warning` means that the script may run to completion with no visible indication that it did not do everything that was expected. Not good.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Output "$vmName : Successfully deployed/updated $ExtensionType"
All the additional diagnostic information contained in the `PSAzureOperationResponse` object is being thrown away! CSS and your fellow engineers will not have kind words when they are trying to troubleshoot a CRI.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $OnboardingStatus.Failed += "$vmName : Failed to install/update $ExtensionType"
All the additional diagnostic information contained in the PSAzureOperationResponse object is being thrown away! CSS and your fellow engineers will not have kind words when they are trying to troubleshoot a CRI.

Note: This means getting a $null response from `Set-VMExtension` will need to be handled differently than when `IsSuccessStatusCode` is `$false`.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
>          }
`AutoUpgradeMinorVersion` needs to a) be preserved during an update and b) should be set for an install.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
>  function Install-VMssExtension {
See all the comments on `Install-VMExtension`.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Warning("$vmName : has an unsupported OS: $osType")
Yes, I see it is existing code.
This message is misleading when a) it is a VMSS, and b) there are no provisioned VMs.

2023-08-28 21:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if ($DcrResourceId) {
We are using the presence/absence of a DCR id to imply whether the person running the script wants to use AMA or the legacy agent. Likewise, not using AMA or the use of the `-ProcessAndDependencies` option indicates configuring the DA.

Rather than having the logic for interpreting the parameters in multiple places, have one place early in the execution of the script, when doing any parameter validation that may be needed, compute a couple of simple Boolean variables, or some other simple state, one for which agent to use and one for whether or not to use the DA.

2023-08-29 21:26 UTC, mthompson83 requested changes
more to follow

2023-08-29 21:26 UTC, mthompson83 commented on Install-VMInsights.ps1
> +function Assign-ManagedIdentityRoles {
This function, `Assign-ManagedIdentityRoles`, is being called for each VM/VMSS selected. However, this does **not** act on a VM/VMSS it acts on a Resource Group.

Hoist the processing up, executing it only once for each resource group.

2023-08-30 20:47 UTC, mthompson83 requested changes
I think I've made it through the whole script now.

2023-08-30 20:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $statusResult = Get-AzVM -ResourceGroupName $vmResourceGroupName -Name $vmName
Please double check this.

I did an experiment and the data returned Get-AzVM without the `-Name` option (i.e., the way we do the query to get all the VMs that will be updated) includes the Identity field. If that is correct, there is no need to do another call to `Get-AzVM`.

Same appears to be true for `Get-AzVMSS`.

2023-08-30 20:47 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $statusResult = Get-AzVM -ResourceGroupName $vmResourceGroupName -Name $vmName
Based upon my experiments, the class of objects in the array returned when `Get-AzVM` or `Get-AzVMSS` is called without the `-Name` option is a subclass of the type of object returned when `-Name` is used to filter to a single VM.

2023-08-30 20:47 UTC, mthompson83 commented on Install-VMInsights.ps1
>      if (!$ResourceGroup -and !$Name) {
Based upon later experiments, using Get-AzVM/Get-AzVMSS without the `-Name` filter returns a collection of objects that are subclasses of the class of object returned when `-Name` is used.

Given my experiments are correct, and we don't need access to properties that are only available in the subclass, then we can get the set of VMs and VMSSs in one shot for each type.

```
$filter_param = @{}
if ($ResourceGroup) {
    $filter_param["ResourceGroupName"] = $ResourceGroup
}
if ($Name) {
    $filter_param["Name"] = $Name
}

$VMs = Get-AzVM -Status @filter_param
$ScaleSets = Get-AzVmss @filter_param

```

2023-08-30 20:47 UTC, mthompson83 commented on Install-VMInsights.ps1
>      if (!$ResourceGroup -and !$Name) {
Very Interesting! The `-Status` flag will add the PowerState field when the `-Name` option is **not** used. But, PowerState is never included when `-Name` is given.

2023-09-13 21:43 UTC, mthompson83 reviewed
Partial review. More to follow.

Please do not push changes until I finish this pass through the code.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if (!$exceptionInfo) {
We've talked about this before:

Do not write
```
if (...) {
    ...
}
else {
   if (...) {
      ...
   }
   # 0 or more elseif
   # Optionally an else
}
```

Use

```
if (...) {
    ...
}
elseif (...) {
      ...
}
# 0 or more elseif
# Optionally an else
```

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if (!$exceptionInfo) {
We've talked about this before.

```
if (...) {
    ....
    throw ...
}
else {
    ...
}
```

Simplifies to
```
if (...) {
    ....
    throw ...
}

...
```

Note: Same simplification applies to `return` in place of `throw`.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                throw [FatalException]::new("$vmName ($vmResourceGroupName) : Failed to lookup extensions", $_)
The message text here is **exactly** the same as on line 303 above. That means when the exception is displayed in the catch block below there will be no way to tell which of these two places was the point of origin. That is detrimental to debuggability/supportability.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    InputParameterObsolete($message, $excepObj, $obsParamType) {
`InputParameterObsolete` is a strange name. It sounds like there was a coding error and the caller of some API used an obsolete input parameter!

Find a better name.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +class FatalException : System.Exception {
None of these three classes are actually using any functionality inherited from the parent class. Either a) leverage the parent class, or b) don't use a parent class.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            $errorMessage = $_.Exception.errorMessage
The `OperationFailed` class does not have an `Exception` field.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            $statusCode = $_Exception.statusCode
`$_Exception` is an undefined variable.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Output "OperationFailed => `n`rStatusCode=$statusCode ReasonPhrase=$reasonPhrase"
```
PS C:\Users\mithomps> Write-Output "line 1 `n`rline 2"
line 1 
line 2

PS C:\Users\mithomps> Write-Output "line 1" "line 2"
line 1
line 2

PS C:\Users\mithomps> 
```

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Output "OperationFailed => `n`rStatusCode=$statusCode ReasonPhrase=$reasonPhrase"
The Windows line end is carriage return - newline, not newline - carriage return.

2023-09-13 21:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Output "OperationFailed => `n`rStatusCode=$statusCode ReasonPhrase=$reasonPhrase"
Asa general rule, try to avoid leaving stray whitespace at the end of an output line.

2023-09-14 21:37 UTC, mthompson83 reviewed
review not complete

2023-09-14 21:37 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $removeResult = Remove-AzVMExtension -ResourceGroupName $vmResourceGroupName -VMName $vmName -Name $extensionName -Force -ErrorAction "Stop"
Consider setting [`$ErrorActionPreference`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#erroractionpreference) to `Stop` and override `-ErrorAction` only in those cases where `Stop` is not desired.

2023-09-14 21:37 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    } catch [System.Management.Automation.ParameterBindingException] {
I doubt this `catch` works:

```
PS /home/mike> Write-Output "RG $vmResourceGroupName" "VM $vmName" "ext $extensionName"; $ex = "not set"; $catch_all = "catch all not set"; try { Remove-AzVMExtension -ResourceGroupName $vmResourceGroupName -VMName $vmName -Name $extensionName -Force -ErrorAction "Stop" } catch [System.Management.Automation.ParameterBindingException] { $ex = $_ } catch { $catch_all = $_ }; Write-Output "---" "ex" $ex catch-all $catch_all
RG tb-edp
VM notexist
ext none
---
ex
not set
catch-all

Remove-AzVMExtension: Resource group 'tb-edp' could not be found.
ErrorCode: ResourceGroupNotFound
ErrorMessage: Resource group 'tb-edp' could not be found.
ErrorTarget: 
StatusCode: 404
ReasonPhrase: Not Found
OperationID : c60f0f75-abc4-4bab-93ed-106a1df95195
```

2023-09-14 21:37 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            throw [FatalException]::new("$vmName ($vmResourceGroupName) : Failed to remove extension $extensionName", $_)
Why is this fatal?

2023-09-14 21:37 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if ($_.ErrorId -eq "NamedParameterNotFound") {
Definitely worth a comment that a non-existent VM or the extension not being present on the VM returns success.

2023-10-17 21:36 UTC, mthompson83 requested changes
Interim comments so you may preview them if you wish. Feel free to ignore them until I finish. Please don't push code changes or mark comments as resolved until the entire review is complete.

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                    Write-Host "$vmlogheader : Extension $extensionName was not chosen to be removed. Skipping Re-install"
The customer was prompted to remove the extension. Why do they need this message? Or, is this message here to cover scenarios where the confirmation prompt kicked in, and they selected no for all?

If this message is needed, consider putting it in `RemoveVMExtension`.

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if($errorCode -eq "ResourceGroupNotFound") {
Use consistent code formatting.
```suggestion
        if ($errorCode -eq "ResourceGroupNotFound") {

```

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $errorCode = ExtractCloudExceptionErrorCode $_
Move `$errorCode = ExtractCloudExceptionErrorCode $_` below the first if statement, immediately above the if statement where `$errorCode` is first referenced. Minimizing the distance between when a variable is set and its first reference improves readability.

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    #ExtensionName -> keep as separate parameter, InstlalParameter that is variable.
Complete this work: `InstallVMExtension` should accept `$extensionName` as a separate parameter.

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                    return $False
Return value for `OnboardVmiWithLaVmWithReInstall` is never used. This is either a defect in the caller or the function doesn't need to return a value.

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmlogheader : Extension $extensionName does not support updating workspace. An uninstall followed by re-install is required"
```suggestion
                Write-Host "$vmlogheader : Extension $extensionName does not support updating workspace. An uninstall followed by re-install is required."

```

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmlogheader : Extension $extensionName does not support updating workspace. An uninstall followed by re-install is required"
Why is this message needed? Why does the customer need to see this message for each of the 5,000 VMs in their subscription?

2023-10-17 21:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                    Write-Host "$vmlogheader : Extension $extensionName was not chosen to be removed. Skipping Re-install"
```suggestion
                    Write-Host "$vmlogheader : Extension $extensionName was not removed. Skipping replacement."

```
- Simplifies the wording of the first sentence.
- Saying the reinstall was skipped, at first glance, sounds like script didn't put it back after uninstalling it. You wouldn't want the mechanic to tell you they skipped reinstall the oil drain plug on your car after doing an oil change.

2023-10-19 19:11 UTC, mthompson83 requested changes
Partial

2023-10-19 19:11 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    $userAssignedManagedIdentityName = $UserAssignedManagedIdentityObject.Name
`$userAssignedManagedIdentityName` is a script parameter. This statement will overwrite the parameter value rather that create a local variable.

2023-10-19 19:11 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($UserAssignedManagedIdentityName) {
`$userAssignedManagedIdentityName` is a mandatory parameter in its parameter set.
Recommendation: move this code into the code path that is only executed for the parameter set that includes it. The null check will then be unneeded.

2023-10-20 15:12 UTC, mthompson83 requested changes
not done yet

2023-10-20 21:51 UTC, mthompson83 requested changes
I think that is it for this review.
Ask questions.
Commit changes.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +
Use blank lines to improve readability. A blank line helps visually separate unrelated "things", especially when a "thing" consists of multiple related things.

- There are three "things" here, the declaration of constants for the LA agent, the DA, and AMA.
- Each "thing" consists of two declarations, the map and the default extension name.

What to fix:
- Remove the blank line above the declaration of `amaExtensionName` because it separates it from the map declaration. As is, it is inconsistent with the other two extension.
- Add a blank line after the declaration of `daExtensionName` to set it off from the declarations below it.

Suggestion: Move the declaration of `processAndDependenciesPublicSettings` closer to where the settings are created for the other extensions. Consider only setting it if it will be needed/used.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +$ErrorActionPreference = "Stop"
Move setting `$ErrorActionPreference` up to the top of the script. As is, any of the code before it is set could error and continue, leaving variables in unpredictable states that could lead to strange/cryptic failures later in the execution.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $ErrorRecord
Readability: Be consistent with formatting `param` blocks. Here the variable name is on a separate line after the data type specifier. In other parts of the code the type and variable are on the same line.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    foreach ($extension in $extensions) {
Consider using a pipe from `Get-AzExtension` to `Foreach-Object` eliminating the `$extensions` variable.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    $invalidOperationParserPattern = "status code '([a-zA-Z]+)'"
Consider whether the pattern `[a-zA-Z]+` may be too restrictive.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $dcrassociation = New-AzDataCollectionRuleAssociation -TargetResourceId $vmId -AssociationName $dcrassociationName -RuleId $DcrResourceId
What will happen if there is a DCRA with the name "VM-Insights-DCR-Association" that references a DCR other than the one identified by `the value of $DcrResourceId`?

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if ($dcrAssociation.DataCollectionRuleId -eq $DcrResourceId) {
General observation: All string comparisons are being done case-insensitive, including hash table keys.
Questions:
- Was this a deliberate design choice?
- If so, does it warrant a comment to document the design intent?
- If not, then is it correct? Are there no string comparisons that should be case sensitive?

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if (!($exceptionMessage -match $invalidOperationParserPattern)){
Duplicated code block see line 597.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    $invalidOperationParserPattern = "status code ([a-zA-Z]+)"
Variable only used once (after removing the duplicate code block). Eliminate the variable.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Host "$vmsslogheader : Data Collection Rule $($dcrAssociation.Name) already associated to the VMSS"
Move the loop into the `try` block so there is no possible code path that allows it to be reached without setting `$dcrAssociationList`.
Consider replacing with a pipe to `Foreach-Object`.

2023-10-20 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if (($null -eq $dcrassociation) -or ($dcrassociation -is [Microsoft.Azure.Management.Monitor.Models.ErrorResponseCommonV2Exception])) {
Move this code block into the try block above where `$dcrassociation` is set to ensure there is no possible code path that allows this code to be reached without setting `$dcrassociation`.

2023-10-25 19:59 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +                Write-Host "$vmlogheader : Extension $extensionName does not support updating workspace. An uninstall followed by re-install is required"
Since this is a high impact task, I think it would be beneficila for customers to know the significance of this step. On other extreme if a customer has only 1 VM, it is essential for the customer to see this VM. Adding a counter to not print a message  more than 'X' times would increase code-complexity - making the above message Write-Verbose would not be a good idea either. The other viable option is to include this in the documentation,shall I take this path

2023-10-25 20:45 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Host "$vmsslogheader : Data Collection Rule $($dcrAssociation.Name) already associated to the VMSS"
Per conversation with Kartik, `ForEach-Object` won't work when the loop needs to be terminated before processing all input objects.

2023-10-26 21:29 UTC, mthompson83 requested changes
In progress update

2023-10-26 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    Write-Host "$vmsslogheader : UpgradePolicy is Manual. Please trigger upgrade of VMSS or call with -TriggerVmssManualVMUpdate"
I am concerned about displaying the prompt "Please trigger upgrade of VMSS or call with -TriggerVmssManualVMUpdate" as the VMSS are being processed.
- Assume most, or all, of the 100's of VMSS are in Manual mode, then this gets displayed 100's of times.
- Assume there is one out of 100's of VMs/VMSSs is in Manual mode, then this is displayed once in the middle of 100's of lines of output.

Can we do better?
- We have the upgrade mode available when presenting the collection of VMs/VMSSs initially. Can we do something to highlight the systems there, and present this advisory once if applicable?
- May at the end of processing the VMs/VMSSs, if there were VMss with Manual upgrade mode, then present one summary message "X VM Scale Sets havd Manual upgrade mode set and were not upgraded. ..."

2023-10-26 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmsslogheader : Failed to upgrade VMSS instance name $scaleSetInstanceName. $($result.Status)"
Be consistent.
```suggestion
                Write-Host "$vmsslogheader : Failed to upgrade VMSS instance name $scaleSetInstanceName, $i of $instanceCount. $($result.Status)"

```

2023-10-26 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $scaleSetInstanceName = $($scaleSetInstance.Name)
Why
```
$scaleSetInstanceName = $($scaleSetInstance.Name)
````
instead of
```
$scaleSetInstanceName = $scaleSetInstance.Name
```

2023-10-26 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        Write-Host "Upgrading $i of $instanceCount"
Recommendation: Move the setting of `$scaleSetInstanceName` above this `Write-Host` statement, then
```suggestion
        Write-Host "Upgrading $scaleSetInstanceName, $i of $instanceCount"

```

2023-10-26 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            #Counter -> consdider throwing exception is hard.
What does this comment "#Counter -> ..." mean?

2023-10-27 19:11 UTC, mthompson83 requested changes
Not quite done.

2023-10-27 19:11 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmsslogheader : Data Collection Rule Id $DcrResourceId already associated to the VMSS"
```suggestion
                Write-Host "$vmsslogheader : Data Collection Rule Id $DcrResourceId already associated with the VMSS."

```

2023-10-27 19:11 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    Write-Host "$vmlogheader : Successfully created data collection rule association"
Be consistent in messages with things that are proper names. Above, it is "Data Collection Rule Association". Here it is "data collection rule association".

Review all customer facing messages for consistent capitalization of VM (Virtual Machine), VMSS (Virtual Machine Scale Set), Resource Group, Data Collection Rule, etc.

2023-10-27 20:22 UTC, mthompson83 requested changes
Done.

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        } catch {
What happens if Azure gets a timeout servicing the request? I expect there will be an exception, but telling the administrator the Resource Group they entered was invalid will not make sense.

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Get-AzResourceGroup -Name $ResourceGroup >$null
As mentioned in a previous comment, a Resource Group name with a wildcard in it, that matches **no** Resource Groups will a) return nothing, and b) not throw an exception. `Get-AzResourceGroup` will return `$null`.

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        Write-Host "Looking up resources in policy assingment $PolicyAssignmentName"
What resources?
```suggestion
        Write-Host "Looking up Virtual Machines in policy assingment $PolicyAssignmentName"

```

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        Write-Host "Getting list of VM's or VM ScaleSets matching criteria specified"
It isn't a possessive.
Don't write geek
```suggestion
        Write-Host "Getting list of VMs or VM Scale Sets matching specified criteria."

```

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            $vmList | ForEach-Object { Write-Host " " "$($_.Name)" }
Why do we need a blank line before each VM name?

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            $vmssList | ForEach-Object { Write-Host " " "$($_.Name)" }
Why do we need a blank line before each VMSS name?

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    Write-Verbose "Scope $ResourceGroupId : $Role has been successfully assigned to $uamiName"
"Scope" is not part of the parameters or customer facing vocabulary of this script. "Scope" is an implementation detail of the API being used by this script. Either use "Resource Group" instead of "Scope" or no label (`"ResourceGroupId : $Role ..."`).

2023-10-27 20:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    Write-Verbose "Scope $ResourceGroupId : Assigning role $Role"
same comment as below about "Scope".

2023-10-30 22:26 UTC, mthompson83 requested changes

2023-10-31 16:04 UTC, mthompson83 requested changes

2023-10-31 16:17 UTC, vpidatala94 commented on Install-VMInsights.ps1
> +            $extensionPublicSettingsJson = $extension.PublicSettings | ConvertFrom-Json
hey this is also counted as success, as there is no data loss.

2023-10-31 18:23 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        if ($scaleSetInstance.InstanceView.Statuses.DisplayStatus -contains "VM deallocated") {
Concern:
- Statuses is a List of statuses
- `DisplayStatus` is the value designed for Human consumption. It could be localized or reworded in the future while keeping the same `Code` value.
- This check is looking for the VM instance being in a specific non-operational state. Is it better skip any VM that is **not** in a specific known good state?

```
PS /home/mike> $vmss[0].InstanceView.Statuses | format-List

Code          : ProvisioningState/succeeded
Level         : Info
DisplayStatus : Provisioning succeeded
Message       : 
Time          : 9/4/2023 8:14:35 PM

Code          : PowerState/running
Level         : Info
DisplayStatus : VM running
Message       : 
Time          : 


PS /home/mike> $vmss[0].InstanceView.Statuses.GetType()    

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     List`1                                   System.Object

PS /home/mike> $vmss[0].InstanceView.Statuses[0] | format-List

Code          : ProvisioningState/succeeded
Level         : Info
DisplayStatus : Provisioning succeeded
Message       : 
Time          : 9/4/2023 8:14:35 PM


PS /home/mike> $vmss[0].InstanceView.Statuses[1] | format-List

Code          : PowerState/running
Level         : Info
DisplayStatus : VM running
Message       : 
Time          : 


PS /home/mike> 
```

2023-10-31 18:27 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $i++
strange counting:
```
VMSS vm_0, 0 of 5 deallocated
VMSS vm_1, 0 of 5 deallocated
VMSS vm_2, 0 of 5 deallocated
Upgrading vm_3, 0 of 5
Upgrading vm_4, 1 of 5
```

2023-10-31 18:53 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Host "$vmsslogheader : Failed to upgrade VMSS instance name $scaleSetInstanceName, $i of $instanceCount. ErrorCode $errorCode. Continuing ..."
We need something in the summary report that will tell the administrator that there were instances that didn't upgrade successfully. As is, if we don't hit the limit and abandon the VMSS, it will count as a success.

2023-10-31 18:57 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        throw [ResourceGroupDoesNotExist]::new($ResourceGroupName)
This is still wrong.

2023-10-31 19:36 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            try {
Reduce indentation of try/catch block.

2023-10-31 19:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        } catch {#if resourceNotFound Exception not found then ignore it.}
The comment needs to be turned into action.

2023-10-31 19:43 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        } catch {}
Need to be selective about what exceptions are caught. As currently written, any is quietly ignored.

2023-10-31 19:45 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($ManualUpgrade -gt 0 -and !$TriggerVmssManualVMUpdate) {
Let's refine this.

2023-10-31 19:49 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                    Write-Host "$vmsslogheader : Successfully onboarded VMInsights"
The formal product name, based upon what I see in the customer documentation, is "VM insights", not "VMInsights".

2023-10-31 19:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        Write-Host "Looking up Virtual Machines in policy assingment $PolicyAssignmentName"
```suggestion
        Write-Host "Looking up Virtual Machines in policy assignment $PolicyAssignmentName"

```

2023-10-31 19:52 UTC, mthompson83 commented on Install-VMInsights.ps1
> +         Write-Host "$vmlogheader : Successfully removed extension $ExtensionName, type $extensionType.$extensionPublisher"
indentation
```suggestion
        Write-Host "$vmlogheader : Successfully removed extension $ExtensionName, type $extensionType.$extensionPublisher"

```

2023-10-31 19:54 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        #TBF by AMCS team - New-AzDataCollectionRuleAssociation allows creating multiple DCRAs for the same {DCR,VMSS} combination.
Replace non-standard abbreviation "TBF".
```suggestion
        #To be fixed by AMCS team - New-AzDataCollectionRuleAssociation allows creating multiple DCRAs for the same {DCR,VMSS} combination.

```

2023-10-31 20:58 UTC, mthompson83 commented on Install-VMInsights.ps1
> +<Optional> Name of policy assignment to onboard VMI for VMs part of its scope with Azure Monitoring Agent (AMA)/Log Analytics Agent (LA)
```suggestion
<Optional> Only include VMs associated with this policy.

```

2023-10-31 20:59 UTC, mthompson83 commented on Install-VMInsights.ps1
> +<Optional> Set this flag to confirm every command in the script.
```suggestion
<Optional> Set this flag to confirm each VM / VMSS.

```

2023-10-31 21:16 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                return $VMObject
This may need a counter for summary. One VM not being changed, but a summary that says everything was successful isn't good.

2023-10-31 21:22 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmsslogheader : Failed to upgrade VMSS instance name $scaleSetInstanceName, $i of $instanceCount. $($result.Status)"
When `$result.Status -ne "Succeeded"` also needs to be part of the unsuccessful count.

2023-10-31 21:24 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                Write-Host "$vmsslogheader : Unable to locate VMSS instance name $scaleSetInstanceName. Continuing ..."
Display the exception, then `Write-Host "... Continuing ..."`

2023-10-31 21:29 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($null -eq $rgObj) {
Oooops on me! In the function `SetManagedIdentityRolesAma`, `$ResourceGroupName` is the function parameter. It will always be **a** Resource Group Name. There are no wildcards. No need to check for null.

2023-10-31 21:32 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    $Rghashtable = @{}
A blank line please to separate `$Rghashtable` from the script blocks.

2023-10-31 21:34 UTC, mthompson83 commented on Install-VMInsights.ps1
> +                #queitly do nothing.
Fix multiple places
```suggestion
                #quietly do nothing.

```

2023-10-31 21:35 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        Write-Host "" "ResourceGroup : $rg"
```suggestion
        Write-Host "ResourceGroup : $rg"

```

2023-11-01 20:32 UTC, mthompson83 requested changes

2023-11-02 15:32 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if (!($PSCmdlet.ShouldProcess($vmlogheader, "Assign User Assigned Managed Identity $userAssignedManagedIdentityName"))) {
Not seeing any changes that appear to address the `-WhatIf` problem we saw yesterday.

2023-11-07 16:28 UTC, mthompson83 requested changes

2023-11-08 14:38 UTC, mthompson83 requested changes

2023-11-08 14:38 UTC, mthompson83 commented on Install-VMInsights.ps1
> +            Write-Host "VMSS instance $scaleSetInstanceName, $i of $instanceCount is not operational. State = $healthstatus"
This was my mistake. I realized last night that the message to the administrator, `"... State = $healthstatus"` is using the internal codes. We do want to use the `Code` values for the logic, but we should use the DisplayStatus for the human facing messages.
```suggestion
            Write-Host "VMSS instance $scaleSetInstanceName, $i of $instanceCount is not operational. State = $($scaleSetInstance.InstanceView.Statuses.DisplayStatus)"

```

2023-11-09 18:00 UTC, mthompson83 requested changes

2023-11-09 18:21 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($null -ne $keys -and $keys.contains($UserAssignedManagedIdentityObject.Id)) {
My oversight for my previous suggestion. Looking at the check we did for power state, etc. and I see an improvement. The `-contains` operator does the right thing when the left operand is `$null`
```suggestion
    if ($keys -contains $UserAssignedManagedIdentityObject.Id) {

```

2023-11-09 18:23 UTC, mthompson83 commented on Install-VMInsights.ps1
> +	Checking if User Assigning Managed Identity is already assigned to VM, if not assigning it
```suggestion
	Checking if User Assigned Managed Identity is already assigned to VM, if not assigning it

```

2023-11-09 18:23 UTC, mthompson83 commented on Install-VMInsights.ps1
> +	Checking if User Assigning Managed Identity is already assigned to VMSS, if not assigning it
```suggestion
	Checking if User Assigned Managed Identity is already assigned to VM, if not assigning it

```

2023-11-09 18:24 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($null -ne $keys -and $keys.contains($UserAssignedManagedIdentityObject.Id)) {
Same simplification of using `-contains`.

2023-11-09 21:51 UTC, mthompson83 requested changes

2023-11-09 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +    if ($AlreadyAssignedIdentityIdList -contains $IdentityIdToAssign) {
```
    if ($AlreadyAssignedIdentityIdList -contains $IdentityIdToAssign) {
        return $True
    }

    return $False
```

reduces to

```
    return $AlreadyAssignedIdentityIdList -contains $IdentityIdToAssign
```

2023-11-09 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        [String[]]
The data type of the value being passed is not a String array. There is an implicit type conversion happening.

```
PS /home/mike> $vm = Get-AzVm -ResourceGroupName "TB-EDP" -Name "rhel841mult"
PS /home/mike> $vm.Identity.UserAssignedIdentities.Keys.GetType()                                                                                                                                                    

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    KeyCollection                            System.Object
```
```
PS /home/mike> $vmss = Get-AzVm -ResourceGroupName "TB-EDP" -Name "w*19*"
PS /home/mike> $vmss.Identity.UserAssignedIdentities.Keys                
/subscriptions/c1c21d53-ea09-4dcf-9c3d-a86941c960cc/resourcegroups/tb-edp/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ForRCTesting
PS /home/mike> $vmss.Identity.UserAssignedIdentities.Keys.GetType()                                                                                                                                                    

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    KeyCollection                            System.Object

```

2023-11-09 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +        $IdentityIdToAssign
Low quality parameter name `IdentityIdToAssign`. This function does **not** do assignments. I suspect it was given this name because of how the function is being used in its caller. High quality parameter names help explain the role of the parameter in the black box behavior of the function, _without regard for how the caller gets the values it passes_.
```suggestion
        $IdentityId

```

2023-11-09 21:51 UTC, mthompson83 commented on Install-VMInsights.ps1
> +function IsUserManagedIdentityAlreadyAssigned {
Reference: [VirtualMachineIdentity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachineidentity?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotne)
```
function IsUserManagedIdentityAssigned {
    <#
        ...
        #>
    [CmdletBinding]
    param
    (
        [Parameter(Mandatory = $True)]
        [Microsoft.Azure.Management.Compute.Models.VirtualMachineIdentity]
        $VmIdentity,
        [Parameter(Mandatory = $True)]
        [String]
        $IdentityId
    )

    return ($VmIdentity.UserAssignedIdentities.Keys -contains $Identity)
}
```

Sample use:
```
    if (IsUserManagedIdentityAlreadyAssigned -VmIdentity $VMssObject.Identity -IdentityId $UserAssignedManagedIdentityObject.Id) {
        Write-Host "$vmsslogheader : User Assigned Managed Identity $userAssignedManagedIdentityName already assigned."
        return $VMssObject
    }
```

Note: If you want to find the data type for `$UserAssignedManagedIdentityObject`, you can
- Change the parameter from `[String]$IdentityId` to `[_whatever-the-correct-type-is_]$Identity`.
- Do the `.Id` in the function instead of in the callers.

2023-11-10 22:10 UTC, mthompson83 requested changes
Proposal for handling VM Extension errors

2023-11-10 22:10 UTC, mthompson83 commented on Install-VMInsights.ps1
> +
```
        if ($errorCode -eq "VMExtensionHandlerNonTransientError") {
            throw [VirtualMachineExtensionError]::new($VMObject, "$($Publisher).$($ExtensionType)", $_.Exception)       
        }

2023-11-13 20:44 UTC, mthompson83 approved these changes

2023-11-13 23:20 UTC, merged